apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        tier: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: MAX_TRIGGER_RETRIES
              value: 2
            - name: ADAPTER_SERVICE_URL
              value : "http://adapter:8080"
            - name: CONNECTION_RETRIES
              value: 20
            - name: CONNECTION_BACKOFF_IN_MS
              value: 5000
            - name: AMQP_URL
              value: "amqp://{{ .Values.global.rabbitmq.username }}:{{ .Values.global.rabbitmq.password }}@rabbitmq:5672"
            - name: AMQP_SCHEDULER_EXCHANGE
              value: "ods_global"
            - name: AMQP_SCHEDULER_QUEUE
              value: "scheduler.datasource-config"
            - name: AMQP_DATASOURCE_CONFIG_TOPIC
              value: "datasource.config.*"
            - name: AMQP_DATASOURCE_CONFIG_CREATED_TOPIC
              value: "datasource.config.created"
            - name: AMQP_DATASOURCE_CONFIG_UPDATED_TOPIC
              value: "datasource.config.updated"
            - name: AMQP_DATASOURCE_CONFIG_DELETED_TOPIC
              value: "datasource.config.deleted"

          ports:
            - containerPort: 8080

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
