replicaCount: 1

image:
  repository: jvalue/open-data-service
  pullPolicy: Always
  tag: notification-latest


global:
  notificationDB:
    username: ""
    password: ""
    database: ""


  rabbitmq:
    username: ""
    password: ""