apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: pipeline
  template:
    metadata:
      labels:
        app: ods
        service: pipeline
    spec:
      containers:
        - name: pipeline-service
          image: jvalue/open-data-service:pipeline-latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10