stages:
  - build
  - integrationtest
  - publish

services:
  - docker:dind

# For predefined environment variables see: https://docs.gitlab.com/ee/ci/variables/
variables:
  # Instruct Testcontainers to use the daemon of DinD.
  # See further: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  # See further: https://docs.docker.com/storage/storagedriver/overlayfs-driver/
  # See further: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
  DOCKER_DRIVER: "overlay2"
  
  ADAPTER_DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/adapter-service
  UI_DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/ui-service
  SCHEDULER_DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/scheduler-service
  STORAGE_POSTGREST_DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/storage-service-postgrest
  STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/storage-service-liquibase



# ----------------- ADAPTER SERVICE --------------------

# BUILD
build-adapter:
  stage: build
  image: docker:stable
  before_script:
    - cd adapter
  script:
    - docker build -t ${ADAPTER_DOCKER_IMAGE_NAME} .
    - mkdir image # Store built image for following CI steps
    - docker save ${ADAPTER_DOCKER_IMAGE_NAME} > image/adapter.tar
  artifacts:
    expire_in: 1 day
    paths:
      - ./adapter/image/adapter.tar

# INEGRATION-TEST
integrationtest-adapter:
  stage: integrationtest
  image: mykiwi/docker
  dependencies:
    - build-adapter
  script:
    - docker load -i ./adapter/image/adapter.tar
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build adapter-service-it
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d adapter-service
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --exit-code-from adapter-service-it adapter-service-it
  after_script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml down

# PUBLISH
publish-docker-adapter:
  stage: publish
  image: docker:stable 
  dependencies:
    - build-adapter
  when: manual
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - cd adapter
  script:
    - docker load -i image/adapter.tar
    - export ADAPTER_VERSION=$(cat ./src/main/resources/application.properties | grep "version =" | awk '{print $3}' | sed "s/[']//g")
    # Tag as version and push
    - docker tag ${ADAPTER_DOCKER_IMAGE_NAME} ${ADAPTER_DOCKER_IMAGE_NAME}:${ADAPTER_VERSION}
    - docker tag ${ADAPTER_DOCKER_IMAGE_NAME} ${ADAPTER_DOCKER_IMAGE_NAME}:latest
    - docker push ${ADAPTER_DOCKER_IMAGE_NAME}:${ADAPTER_VERSION}
    - docker push ${ADAPTER_DOCKER_IMAGE_NAME}:latest


# ----------------- UI SERVICE --------------------

# BUILD
build-ui:
  stage: build
  image: docker:stable
  before_script:
    - cd ui
  script:
    - "docker build -t ${UI_DOCKER_IMAGE_NAME} ."
    - mkdir image # Store built image for following CI steps
    - docker save ${UI_DOCKER_IMAGE_NAME} > image/ui.tar
  artifacts:
    expire_in: 1 day
    paths:
      - ./ui/image

# PUBLISH
publish-docker-ui:
  stage: publish
  image: docker:stable 
  dependencies:
    - build-ui
  when: manual
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - cd ui
  script:
    - docker load -i ./image/ui.tar
    - export UI_VERSION=$(cat package.json | grep "version" | awk '{print $2}' | sed 's/[,"]//g')
    # Tag as version and push
    - docker tag ${UI_DOCKER_IMAGE_NAME} ${UI_DOCKER_IMAGE_NAME}:${UI_VERSION}
    - docker tag ${UI_DOCKER_IMAGE_NAME} ${UI_DOCKER_IMAGE_NAME}:latest
    - docker push ${UI_DOCKER_IMAGE_NAME}:${UI_VERSION}
    - docker push ${UI_DOCKER_IMAGE_NAME}:latest


# ----------------- Storage SERVICE --------------------

# BUILD
build-storage:
  stage: build
  image: docker:stable
  before_script:
    - cd storage
  script:
    - "docker build -t ${STORAGE_POSTGREST_DOCKER_IMAGE_NAME} ./docker/postgrest/"
    - "docker build -t ${STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME} ./docker/liquibase/"
    - mkdir image # Store built image for following CI steps
    - docker save ${STORAGE_POSTGREST_DOCKER_IMAGE_NAME} > image/storage_postgrest.tar
    - docker save ${STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME} > image/storage_liquibase.tar
  artifacts:
    expire_in: 1 day
    paths:
      - ./storage/image


# INEGRATION-TEST
integrationtest-storage:
  stage: integrationtest
  image: mykiwi/docker
  dependencies:
    - build-storage
  script:
    - docker load -i ./storage/image/storage_postgrest.tar
    - docker load -i ./storage/image/storage_liquibase.tar
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build storage-service-it
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d storage-service-db
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d storage-service-db-liquibase
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d storage-service
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --exit-code-from storage-service-it storage-service-it
  after_script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml down


# PUBLISH
publish-docker-storage:
  stage: publish
  image: docker:stable 
  dependencies:
    - build-storage
  when: manual
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - cd storage
  script:
    - docker load -i ./image/storage_postgrest.tar
    - docker load -i ./image/storage_liquibase.tar
    - export STORAGE_VERSION=$(cat version.txt | grep "VERSION" | awk '{print $3}' | sed 's/[,"]//g')
    # Tag as version and push
    - docker tag ${STORAGE_POSTGREST_DOCKER_IMAGE_NAME} ${STORAGE_POSTGREST_DOCKER_IMAGE_NAME}:${STORAGE_VERSION}
    - docker tag ${STORAGE_POSTGREST_DOCKER_IMAGE_NAME} ${STORAGE_POSTGREST_DOCKER_IMAGE_NAME}:latest
    - docker tag ${STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME} ${STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME}:${STORAGE_VERSION}
    - docker tag ${STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME} ${STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME}:latest
    - docker push ${STORAGE_POSTGREST_DOCKER_IMAGE_NAME}:${STORAGE_VERSION}
    - docker push ${STORAGE_POSTGREST_DOCKER_IMAGE_NAME}:latest
    - docker push ${STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME}:${STORAGE_VERSION}
    - docker push ${STORAGE_LIQUIBASE_DOCKER_IMAGE_NAME}:latest

# ----------------- Scheduler SERVICE --------------------

# BUILD
build-scheduler:
  stage: build
  image: docker:stable
  before_script:
    - cd scheduler
  script:
    - "docker build -t ${SCHEDULER_DOCKER_IMAGE_NAME} ."
    - mkdir image # Store built image for following CI steps
    - docker save ${SCHEDULER_DOCKER_IMAGE_NAME} > image/scheduler.tar
  artifacts:
    expire_in: 1 day
    paths:
      - ./scheduler/image


# INEGRATION-TEST
integrationtest-scheduler:
  stage: integrationtest
  image: mykiwi/docker
  dependencies:
    - build-scheduler
  script:
    - docker load -i ./scheduler/image/scheduler.tar
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build scheduler-service-it
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d scheduler-service
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --exit-code-from scheduler-service-it scheduler-service-it
  after_script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml down


# PUBLISH
publish-docker-scheduler:
  stage: publish
  image: docker:stable 
  dependencies:
    - build-scheduler
  when: manual
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - cd scheduler
  script:
    - docker load -i ./image/scheduler.tar
    - export SCHEDULER_VERSION=$(cat package.json | grep "version" | awk '{print $2}' | sed 's/[,"]//g')
    # Tag as version and push
    - docker tag ${SCHEDULER_DOCKER_IMAGE_NAME} ${SCHEDULER_DOCKER_IMAGE_NAME}:${SCHEDULER_VERSION}
    - docker tag ${SCHEDULER_DOCKER_IMAGE_NAME} ${SCHEDULER_DOCKER_IMAGE_NAME}:latest
    - docker push ${SCHEDULER_DOCKER_IMAGE_NAME}:${SCHEDULER_VERSION}
    - docker push ${SCHEDULER_DOCKER_IMAGE_NAME}:latest