apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: adapter-db
  name: adapter-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: adapter-db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_USER
          value: adapterservice
        image: postgres
        name: adapter-db
        resources: {}
      restartPolicy: Always
status: {}
