# Service configurations for all microservices
# has to be specified by environment files

version: '3.7'


volumes:
  auth_postgres_data:
    driver: local

services:

  # ----------------- UI SERVICE (/ui) --------------------
  ui:
    image: registry.gitlab.com/profoss/open-data-service/ods-main/ui-service
    build:
      context: ./ui/
      args:
        UI_BASE_URL: /
        AUTH_SERVICE_URL: /auth
        CORE_SERVICE_URL: /api/core
        STORAGE_SERVICE_URL: /api/storage
        TRANSFORMATION_SERVICE_URL: /api/transformation
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-ui.rule=PathPrefix(`/`)"
      - "traefik.http.services.ui.loadbalancer.server.port=8080"

  # ----------------- AUTH SERVICE (/auth) --------------------
  auth-db:
    image: postgres
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  auth:
    image: registry.gitlab.com/profoss/open-data-service/ods-main/auth-service
    build:
      context: ./auth/
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: auth-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_LOGLEVEL: INFO
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"

  # ----------------- ADAPTER SERVICE (/adapter) --------------------
  adapter:
    image: registry.gitlab.com/profoss/open-data-service/ods-main/adapter-service
    build:
      context: ./adapter/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-adapter.rule=PathPrefix(`/api/adapter`)"
      - "traefik.http.routers.to-adapter.middlewares=adapter-stripprefix@docker"
      - "traefik.http.middlewares.adapter-stripprefix.stripprefix.prefixes=/api/adapter"
      - "traefik.http.services.adapter.loadbalancer.server.port=8080"

  # ----------------- SCHEDULER SERVICE (/scheduler) --------------------
  scheduler:
    image: registry.gitlab.com/profoss/open-data-service/ods-main/scheduler-service
    build:
      context: ./scheduler/
    environment:
      CONFIG_SERVICE_URL: http://core:8080
      ADAPTER_SERVICE_URL: http://adapter:8080
      TRANSFORMATION_SERVICE_URL: http://transformation:8080
      STORAGE_SERVICE_URL: http://storage:3000
      INITIAL_CONNECTION_RETRIES: 20
      INITIAL_CONNECTION_RETRY_BACKOFF: 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-scheduler.rule=PathPrefix(`/api/scheduler`)"
      - "traefik.http.routers.to-scheduler.middlewares=scheduler-stripprefix@docker"
      - "traefik.http.middlewares.scheduler-stripprefix.stripprefix.prefixes=/api/scheduler"

  # ----------------- STORAGE SERVICE (/scheduler) --------------------
  storage: # Wraps postgres database with API
    image: registry.gitlab.com/profoss/open-data-service/ods-main/storage-service-postgrest
    build: ./storage/postgrest/
    environment:
      DATABASE_HOST: storage-db
      DATABASE_PORT: 5432
      DATABASE_NAME: ods
      DATABASE_USER: postgrest
      DATABASE_PW: postgres-wrapper-pw
    depends_on:
      - storage-db
      - storage-db-liquibase # TODO: make sure the migration runs through before reading db structure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-storage.rule=PathPrefix(`/api/storage`)"
      - "traefik.http.routers.to-storage.middlewares=storage-stripprefix@docker,storage-addaccept@docker"
      - "traefik.http.middlewares.storage-stripprefix.stripprefix.prefixes=/api/storage"
      - "traefik.http.middlewares.storage-addaccept.headers.customrequestheaders.Accept=application/json" # Firefox Browser Support
      - "traefik.http.services.storage.loadbalancer.server.port=3000"

  storage-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ods
      POSTGRES_USER: ods_admin
      POSTGRES_PASSWORD: ods_pw
  # Uncomment this if you want to persist the data.
  # volumes:
  #   - "./pgdata:/var/lib/postgresql/data"

  storage-db-ui: # management UI for Postgres
    image: adminer

  storage-db-liquibase: # perform database migration on start up
    image: registry.gitlab.com/profoss/open-data-service/ods-main/storage-service-liquibase
    build: ./storage/liquibase/ # TODO: Sql Injection is currently
    environment:
      DATABASE_HOST: storage-db
      DATABASE_PORT: 5432
      DATABASE_NAME: ods
      DATABASE_USER: ods_admin
      DATABASE_PW: ods_pw

  storage-swagger: # API documentation for storage service
    image: swaggerapi/swagger-ui
    environment:
      API_URL: http://localhost:9400/

  # ----------------- TRANSFORMATION SERVICE (/transformation) --------------------
  transformation:
    image: registry.gitlab.com/profoss/open-data-service/ods-main/transformation-service
    build:
      context: ./transformation/
    environment:
      AUTH_ENABLED: 'false' #TODO: turn to true as soon as it works!
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-transformation.rule=PathPrefix(`/api/transformation`)"
      - "traefik.http.routers.to-transformation.middlewares=transformation-stripprefix@docker"
      - "traefik.http.middlewares.transformation-stripprefix.stripprefix.prefixes=/api/transformation"
      - "traefik.http.services.transformation.loadbalancer.server.port=8080"


  # ----------------- CORE SERVICE (/core) --------------------
  core:
    image: registry.gitlab.com/profoss/open-data-service/ods-main/core-service
    build:
      context: ./core/
    environment:
      - DB_URL=jdbc:postgresql://core-db:5432/coreservice
    depends_on:
      - core-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.to-core.rule=PathPrefix(`/api/core`)"
      - "traefik.http.routers.to-core.middlewares=core-stripprefix@docker"
      - "traefik.http.middlewares.core-stripprefix.stripprefix.prefixes=/api/core"
      - "traefik.http.services.core.loadbalancer.server.port=8080"

  core-db:
    image: postgres
    environment:
      - POSTGRES_USER=coreservice
      - POSTGRES_PASSWORD=admin

# -------------------- EDGE SERVER (PORT 9000) -----------------------------
  edge:
    image: traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --providers.docker # enable label annotations in compose file
      - --providers.docker.exposedByDefault=false
      - --api.insecure # Dashboard: don't do that in production
      # - --log.level=DEBUG
    ports:
      - "9000:80"     # The HTTP port
      - "9001:8080"   # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
