version: '3.7'

services:
# --------------------- SYSTEM TEST ----------------------------------------
  system-test:
    depends_on:
      - mock-server
    labels: # traefic reverse-proxy config
      - "traefik.backend=system-test"
      - "traefik.frontend.rule=PathPrefixStrip:/system-test"
      - "traefik.frontend.passHostHeader=true"

    build:
      context: ./system-test/

    image: open-data-service/ods-main/system-test

    environment:
      CORE_API: http://core-service:8080
      STORAGE_API: http://storage-service:3000
      TRANSFORMATION_API: http://transformation-service:8080
      SCHEDULER_API: http://scheduler-service:8080
      ADAPTER_API: http://adapter-service:8080
      MOCK_SERVER_API: http://mock-server:8080

  mock-server:
    labels:
      - "traefik.backend=mock-server"
      - "traefik.frontend.rule=PathPrefixStrip:/mock-server"
      - "traefik.frontend.passHostHeader=true"

    build:
      context: ./system-test/
      dockerfile: Dockerfiles.mocks

    environment:
      MOCK_SERVER_PORT: 8080

