# Overwrite service configurations of global docker-compose.yml
# for the CI ENVIRONMENT, including MOCKS and INTEGRATION TESTS

version: '3.7'

services:

  # ----------------- ADAPTER SERVICE   (PORTS 9000 - 9099) --------------------
  adapter-service-it:
    build:
      dockerfile: Dockerfile
      context: ./adapter/integration-test/
    image: open-data-service/ods-main/adapter-service-it
    environment:
      ADAPTER_API: http://adapter-service:8080
      MOCK_SERVER_HOST: adapter-service-it
      MOCK_SERVER_PORT: 8081

  # ----------------- SCHEDULER SERVICE (PORTS 9300 - 9399) --------------------
  scheduler-service:
    ports:
      - "9300:8080"
    environment:
      CONFIG_SERVICE_URL: http://scheduler-service-it:8081
      ADAPTER_SERVICE_URL: http://scheduler-service-it:8082
      TRANSFORMATION_SERVICE_URL: http://scheduler-service-it:8083
      STORAGE_SERVICE_URL: http://scheduler-service-it:8084
  scheduler-service-it:
    build:
      context: ./scheduler/integration-test/
    environment:
      SCHEDULER_API: http://scheduler-service:8080
      MOCK_CORE_HOST: scheduler-service-it
      MOCK_CORE_PORT: 8081
      MOCK_ADAPTER_HOST: scheduler-service-it
      MOCK_ADAPTER_PORT: 8082
      MOCK_TRANSFORMATION_HOST: scheduler-service-it
      MOCK_TRANSFORMATION_PORT: 8083
      MOCK_STORAGE_HOST: scheduler-service-it
      MOCK_STORAGE_PORT: 8084


  # ----------------- STORAGE SERVICE (PORTS 9400 - 9499) --------------------
  storage-service-it:
    build:
      context: ./storage/integration-test
    image: open-data-service/ods-main/storage-service-it
    environment:
      STORAGE_API: http://storage-service:3000

  # ----------------- TRANSFORMATION SERVICE (PORTS 9500 - 9599) --------------------
  transformation-service:
    environment:
      AUTH_ENABLED: 'false'

  transformation-service-it:
    build:
      context: ./transformation/integration-test/
    environment:
      TRANSFORMATION_API: http://transformation-service:8080
      MOCK_RECEIVER_HOST: transformation-service-it
      MOCK_RECEIVER_PORT: 8081

  # ----------------- CORE SERVICE (PORTS 9600 - 9599) --------------------
  core-service-it:
    build:
      context: ./core/integration-test
    image: open-data-service/ods-main/core-service-it
    environment:
      CORE_API: http://core-service:8080

