apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (HEAD)
    traefik.enable: "true"
    traefik.http.middlewares.amqp-stripprefix.stripprefix.prefixes: /api/amqp
    traefik.http.routers.to-amqp.middlewares: amqp-stripprefix@docker
    traefik.http.routers.to-amqp.rule: PathPrefix(`/api/amqp`)
    traefik.http.services.amqp.loadbalancer.server.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: "15672"
    port: 15672
    targetPort: 15672
  - name: "5672"
    port: 5672
    targetPort: 5672
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}
