apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (HEAD)
    traefik.enable: "true"
    traefik.http.middlewares.scheduler-stripprefix.stripprefix.prefixes: /api/scheduler
    traefik.http.routers.to-scheduler.middlewares: scheduler-stripprefix@docker
    traefik.http.routers.to-scheduler.rule: PathPrefix(`/api/scheduler`)
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (HEAD)
        traefik.enable: "true"
        traefik.http.middlewares.scheduler-stripprefix.stripprefix.prefixes: /api/scheduler
        traefik.http.routers.to-scheduler.middlewares: scheduler-stripprefix@docker
        traefik.http.routers.to-scheduler.rule: PathPrefix(`/api/scheduler`)
      creationTimestamp: null
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
      - env:
        - name: ADAPTER_SERVICE_URL
          value: http://adapter:8080
        - name: CONNECTION_BACKOFF_IN_MS
          value: "5000"
        - name: CONNECTION_RETRIES
          value: "20"
        - name: MAX_TRIGGER_RETRIES
          value: "2"
        image: /scheduler
        name: scheduler
        resources: {}
      restartPolicy: Always
status: {}
