apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (HEAD)
    traefik.enable: "true"
    traefik.http.middlewares.storage-mq-stripprefix.stripprefix.prefixes: /api/storage-mq
    traefik.http.routers.to-storage-mq.middlewares: storage-mq-stripprefix@docker
    traefik.http.routers.to-storage-mq.rule: PathPrefix(`/api/storage-mq`)
    traefik.http.services.storage-mq.loadbalancer.server.port: "8080"
  creationTimestamp: null
  labels:
    io.kompose.service: storage-mq
  name: storage-mq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (HEAD)
        traefik.enable: "true"
        traefik.http.middlewares.storage-mq-stripprefix.stripprefix.prefixes: /api/storage-mq
        traefik.http.routers.to-storage-mq.middlewares: storage-mq-stripprefix@docker
        traefik.http.routers.to-storage-mq.rule: PathPrefix(`/api/storage-mq`)
        traefik.http.services.storage-mq.loadbalancer.server.port: "8080"
      creationTimestamp: null
      labels:
        io.kompose.service: storage-mq
    spec:
      containers:
      - env:
        - name: AMQP_PIPELINE_CONFIG_CREATED_TOPIC
          value: pipeline.config.created
        - name: AMQP_PIPELINE_CONFIG_DELETED_TOPIC
          value: pipeline.config.deleted
        - name: AMQP_PIPELINE_CONFIG_EXCHANGE
          value: ods_global
        - name: AMQP_PIPELINE_CONFIG_QUEUE
          value: storage-mq.pipeline-config
        - name: AMQP_PIPELINE_CONFIG_TOPIC
          value: pipeline.config.*
        - name: AMQP_PIPELINE_EXECUTION_EXCHANGE
          value: ods_global
        - name: AMQP_PIPELINE_EXECUTION_QUEUE
          value: storage-mq.pipeline-execution
        - name: AMQP_PIPELINE_EXECUTION_SUCCESS_TOPIC
          value: pipeline.execution.success
        - name: AMQP_PIPELINE_EXECUTION_TOPIC
          value: pipeline.execution.*
        - name: AMQP_URL
          value: amqp://rabbit_adm:R4bb!7_4DM_p4SS@rabbitmq:5672
        - name: CONNECTION_BACKOFF_IN_MS
          value: "2000"
        - name: CONNECTION_RETRIES
          value: "30"
        - name: POSTGRES_DB
          value: ods
        - name: POSTGRES_HOST
          value: storage-db
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_PW
          value: storagemq-pw
        - name: POSTGRES_SCHEMA
          value: storage
        - name: POSTGRES_USER
          value: storagemq
        image: /storage-mq
        name: storage-mq
        resources: {}
      restartPolicy: Always
status: {}
