apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: storage-swagger
  name: storage-swagger
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: storage-swagger
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://localhost:9400/
        image: swaggerapi/swagger-ui
        name: storage-swagger
        resources: {}
      restartPolicy: Always
status: {}
