apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  backend:
    serviceName: ui-service
    servicePort: 80
  rules:
  - http:
      paths:
      - path: "/api/adapter"
        #pathType: "Prefix"
        backend:
          serviceName: adapter-service
          servicePort: 8080
      - path: "/api/scheduler"
        #pathType: "Prefix"
        backend:
          serviceName: scheduler-service
          servicePort: 8080
      - path: "/api/storage-mq"
        #pathType: "Prefix"
        backend:
          serviceName: storage-mq-service
          servicePort: 8080
      - path: "/api/storage"
        #pathType: "Prefix"
        backend:
          serviceName: storage-service
          servicePort: 80
      - path: "/api/pipelines"
        #pathType: "Prefix"
        backend:
          serviceName: pipeline-service
          servicePort: 8080
      - path: "/api/notification"
        #pathType: "Prefix"
        backend:
          serviceName: notification-service
          servicePort: 8080