apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-db-deployment
  namespace: {{NAMESPACE}}
  labels:
    app: ods
    service: core-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: core-db
  template:
    metadata:
      labels:
        app: ods
        service: core-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: "coreservice"
        - name: POSTGRES_PASSWORD
          value: "admin"
        image: postgres
        imagePullPolicy: Always
        name: core-db
        resources: {}
        ports:
        - containerPort: 5432
      restartPolicy: Always
status: {}
