apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-db-deployment
  namespace: {{NAMESPACE}}
  labels:
    app: ods
    service: storage-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ods
      service: storage-db
  template:
    metadata:
      labels:
        app: ods
        service: storage-db
    spec:
      imagePullSecrets:
      - name: ods-registry-secret
      containers:
      - image: postgres:12-alpine
        imagePullPolicy: Always
        name: storage-db
        resources: {}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "ods"
        - name: POSTGRES_USER
          value: "ods_admin"
        - name: POSTGRES_PASSWORD
          value: "ods_pw"
      restartPolicy: Always
status: {}
