apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  namespace: {{NAMESPACE}}
  labels:
    app: ods
spec:
  selector:
    service: auth-db
  ports:
    - protocol: TCP
      port: 5432 
      targetPort: 5432
status:
  loadBalancer: {}

