apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: {{NAMESPACE}}
  labels:
    app: ods
spec:
  selector:
    service: core
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}

