apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: {{NAMESPACE}}
  labels:
    app: ods
spec:
  selector:
    service: scheduler
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}

