apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: {{NAMESPACE}}
  labels:
    app: ods
spec:
  selector:
    service: storage
  ports:
    - name: storage
      protocol: TCP
      port: 3000
      targetPort: 3000
status:
  loadBalancer: {}

