apiVersion: v2
name: Open Data Service (ODS)
description: An application which can collect data from multiple sources simulataneously, process that data and then offer an improved version to its clients.

version: 0.0.1

type: application