name: Storage Build & Test & Publish

on: [push]

jobs:
  storage-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker-compose -f docker-compose.yml build storage
          docker-compose -f docker-compose.yml build storage-db-liquibase

      - name: Integration-test
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml build storage-it
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d storage-db
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up storage-db-liquibase
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d storage
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --exit-code-from storage-it storage-it
          docker-compose logs
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml down

      - name: Push to registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

          STORAGE_VERSION=$(grep "VERSION" ./storage/version.txt | awk '{print $3}' | sed 's/[,"]//g')

          IMAGE_ID_STORAGE=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/storage
          IMAGE_ID_LIQUIBASE=$(sed -n 's/^DOCKER_REGISTRY=//p' .env)/storage-db-liquibase

          docker tag $IMAGE_ID_STORAGE $IMAGE_ID_STORAGE:$STORAGE_VERSION
          docker tag $IMAGE_ID_STORAGE $IMAGE_ID_STORAGE:latest

          docker tag $IMAGE_ID_LIQUIBASE $IMAGE_ID_LIQUIBASE:$STORAGE_VERSION
          docker tag $IMAGE_ID_LIQUIBASE $IMAGE_ID_LIQUIBASE:latest

          docker push $IMAGE_ID_STORAGE:$STORAGE_VERSION
          docker push $IMAGE_ID_STORAGE:latest

          docker push $IMAGE_ID_LIQUIBASE:$STORAGE_VERSION
          docker push $IMAGE_ID_LIQUIBASE:latest
